version: '3'

volumes:
  data:

services:
  db:
    image: mysql:5.6
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=socialmedia

  phpadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    ports:
      - '8080:80'
    environment:
      - PMA_ARBITRARY=1

  apache:
    image: php:7.2-apache
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./html:/var/www/html
    depends_on:
      - db
    links:
      - db